# Generated by Django 3.2.12 on 2023-03-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
