# Generated by Django 3.2.12 on 2023-03-20 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20230319_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='des',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_des', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_price', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_url', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='auctions.listing'),
        ),
    ]
