# Generated by Django 3.2.12 on 2023-03-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20230320_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='des',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='url',
        ),
    ]
