# Generated by Django 3.2.12 on 2023-03-24 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20230324_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
